### PR TITLE
Removed layers

### PR DESCRIPTION
**Pull request by RoyProctor**

### CODE REVIEW

**Comment by matthewcarr** [comment]
I think this could really be the impetus for change this project is looking for.
Thanks Roy, very cool.

**Comment by Robbien92** [comment]
What's wrong with layers? Cakes have layers. **OGRES HAVE LAYERS**.

**Comment by RoyProctor** [comment]
Surprise test of strength Exile!

**Comment by matthewcarr** [comment]
didn't even mention onions have layers smh

**Comment by matthewcarr** [comment]
onions did nothing wrong, don't @ me

**Pull request closed without merging**
